---
- name: Automated Security Hardening
  hosts: localhost
  become: yes
  vars:
    ufw_installed: "ufw"  # Name of the firewall package
    nginx_conf_path: "/etc/nginx"
    nginx_log_path: "/var/log/nginx"
    nginx_forbidden_dir: "/var/www/html/forbidden"
    apparmor_profile_path: "/etc/apparmor.d"
    sshd_config_path: "/etc/ssh/sshd_config"
    oval_content_url: "https://security-metadata.canonical.com/oval/com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml.bz2"
    report_directory: "{{ ansible_env.HOME }}"
  tasks:
    # Task 1: Configure firewall rules using ufw
    - name: Ensure ufw package is installed
      apt:
        name: "{{ ufw_installed }}"
        state: present

    - name: Allow SSH through firewall
      command: ufw allow ssh

    - name: Allow HTTP through firewall
      command: ufw allow http

    - name: Allow HTTPS through firewall
      command: ufw allow https

    - name: Enable firewall
      command: ufw --force enable

    # Task 2: Install apparmor-utils and Nginx, and create custom AppArmor profile
    - name: Install AppArmor utilities
      apt:
        name: apparmor-utils
        state: present

    # Step 2: Creating Custom Profiles
    - name: Generate AppArmor profile for Nginx
      command: aa-autodep nginx
      become: yes

    - name: Set Nginx profile to complain mode
      command: aa-complain /usr/sbin/nginx
      become: yes

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

    # Step 3: Enforcing the Profile
    - name: Create custom AppArmor profile for Nginx
      copy:
        src: nginx.apparmor
        dest: /etc/apparmor.d/usr.sbin.nginx
      become: yes

    - name: Create forbidden directory
      file:
        path: "{{ nginx_forbidden_dir }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Create index.html file in forbidden directory
      copy:
        content: "<h1>This is forbidden.</h1>"
        dest: "{{ nginx_forbidden_dir }}/index.html"
      become: yes

    - name: Load and enforce the AppArmor profile for Nginx
      command: apparmor_parser -r /etc/apparmor.d/usr.sbin.nginx
      become: yes

    - name: Enforce the AppArmor profile for Nginx
      command: aa-enforce /usr/sbin/nginx
      become: yes

    - name: Restart Nginx service to apply the AppArmor profile
      service:
        name: nginx
        state: restarted

# Task 3: Enforce secure configuration settings
- name: Configuration Management
  hosts: localhost
  become: yes
  tasks:
    - name: Set secure SSH configuration
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^X11Forwarding', line: 'X11Forwarding no' }
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

# Task 4: Apply CIS benchmarks
- name: Continuous Compliance Monitoring
  hosts: localhost
  become: yes
  tasks:
    - name: Install necessary packages for OpenSCAP
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libopenscap8
        - python-openscap
        - ssg-base
        - ssg-debderived
        - ssg-debian
        - ssg-nondebian
        - ssg-applications
        - cmake
        - make
        - expat
        - libxml2-utils
        - ninja-build
        - python3-jinja2
        - python3-yaml
        - xsltproc

    - name: Download OVAL Content
      command: "wget {{ oval_content_url }}"
      args:
        chdir: "{{ report_directory }}"
      register: download_result
      changed_when: download_result.stdout.find('saved') != -1

    - name: Unzip OVAL Content
      command: "bunzip2 -f com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml.bz2"
      args:
        chdir: "{{ report_directory }}"
      register: unzip_result
      changed_when: unzip_result.stdout.find('done') != -1

    - name: Run Vulnerability Scan
      command: "oscap oval eval --report report.html com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml"
      args:
        chdir: "{{ report_directory }}"
      register: scan_result

    - name: Display Scan Report
      debug:
        msg: "Vulnerability Scan Report: file://{{ report_directory }}/report.html"
      when: scan_result.rc == 0
