---
- name: Automated Security Hardening
  hosts: localhost
  become: yes
  vars:
    ufw_installed: "ufw"  # Name of the firewall package
    nginx_conf_path: "/etc/nginx"
    nginx_log_path: "/var/log/nginx"
    nginx_forbidden_dir: "/var/www/html/forbidden"
    apparmor_profile_path: "/etc/apparmor.d"
    sshd_config_path: "/etc/ssh/sshd_config"
    oval_content_url: "https://security-metadata.canonical.com/oval/com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml.bz2"
    report_directory: "{{ ansible_env.HOME }}"
  tasks:
    # Task 1: Configure firewall rules using ufw
    - name: Ensure ufw package is installed
      apt:
        name: "{{ ufw_installed }}"
        state: present

    - name: Allow SSH through firewall
      command: ufw allow ssh

    - name: Allow HTTP through firewall
      command: ufw allow http

    - name: Allow HTTPS through firewall
      command: ufw allow https

    - name: Enable firewall
      command: ufw --force enable

     # Task 2: Install apparmor-utils and Nginx
   ---
- name: Install and configure AppArmor for Nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Install AppArmor utilities
      apt:
        name: apparmor-utils
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create directory for forbidden content
      file:
        path: /var/www/html/forbidden
        state: directory
        mode: 0755

    - name: Create forbidden content file
      copy:
        content: "<h1>This is forbidden.</h1>"
        dest: /var/www/html/forbidden/index.html

    - name: Generate AppArmor profile for Nginx
      command: aa-autodep nginx

    - name: Configure Nginx AppArmor profile
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.nginx
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "/var/www/html/forbidden/* r,"
        - "/etc/group r,"
        - "/etc/nginx/conf.d/ r,"
        - "/etc/nginx/mime.types r,"
        - "/etc/nginx/nginx.conf r,"
        - "/etc/nsswitch.conf r,"
        - "/etc/passwd r,"
        - "/etc/ssl/openssl.cnf r,"
        - "/run/nginx.pid rw,"
        - "/usr/sbin/nginx mr,"
        - "/var/log/nginx/access.log w,"
        - "/var/log/nginx/error.log w,"
        - "owner /etc/nginx/modules-enabled/ r,"
        - "owner /etc/nginx/sites-available/default r,"
        - "owner /etc/nginx/sites-enabled/ r,"
        - "owner /usr/share/nginx/modules-available/mod-http-geoip.conf r,"
        - "owner /usr/share/nginx/modules-available/mod-http-image-filter.conf r,"
        - "owner /usr/share/nginx/modules-available/mod-http-xslt-filter.conf r,"
        - "owner /usr/share/nginx/modules-available/mod-mail.conf r,"
        - "owner /usr/share/nginx/modules-available/mod-stream-geoip.conf r,"
        - "owner /usr/share/nginx/modules-available/mod-stream.conf r,"

    - name: Load Nginx AppArmor profile
      command: apparmor_parser -r /etc/apparmor.d/usr.sbin.nginx

    - name: Enforce Nginx AppArmor profile
      command: aa-enforce /usr/sbin/nginx

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

# Task 3: Enforce secure configuration settings
- name: Configuration Management
  hosts: localhost
  become: yes
  tasks:
    - name: Set secure SSH configuration
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^X11Forwarding', line: 'X11Forwarding no' }
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

# Task 4: Apply CIS benchmarks
- name: Continuous Compliance Monitoring
  hosts: localhost
  become: yes
  tasks:
    - name: Install necessary packages for OpenSCAP
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libopenscap8
        - python-openscap
        - ssg-base
        - ssg-debderived
        - ssg-debian
        - ssg-nondebian
        - ssg-applications
        - cmake
        - make
        - expat
        - libxml2-utils
        - ninja-build
        - python3-jinja2
        - python3-yaml
        - xsltproc

    - name: Download OVAL Content
      command: "wget {{ oval_content_url }}"
      args:
        chdir: "{{ report_directory }}"
      register: download_result
      changed_when: download_result.stdout.find('saved') != -1

    - name: Unzip OVAL Content
      command: "bunzip2 -f com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml.bz2"
      args:
        chdir: "{{ report_directory }}"
      register: unzip_result
      changed_when: unzip_result.stdout.find('done') != -1

    - name: Run Vulnerability Scan
      command: "oscap oval eval --report report.html com.ubuntu.{{ ansible_distribution_release }}.usn.oval.xml"
      args:
        chdir: "{{ report_directory }}"
      register: scan_result

    - name: Display Scan Report
      debug:
        msg: "Vulnerability Scan Report: file://{{ report_directory }}/report.html"
      when: scan_result.rc == 0
