- hosts: remote
  become: true
  pre_tasks:
    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        path: "/home/rodriguez/hoa9/ca-certificate.key"
        passphrase: "{{ secret_ca_passphrase }}"

  tasks:
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "/home/rodriguez/hoa9/ca-certificate.key"
        privatekey_passphrase: "abc123"
        common_name: Ansible CA
        use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr

    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "/home/rodriguez/hoa9/ca-certificate.pem"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "/home/rodriguez/hoa9/ca-certificate.key"
        privatekey_passphrase: "abc123"
        provider: selfsigned
